version: '3.8'

services:
  backend:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: npm run server
    dns:
      - 8.8.8.8
      - 1.1.1.1

  nginx:
    build:
      context: ./client
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

